export const API_ARTICLE_QUERY_MS = 'ARTICLE_QUERY';
export const API_ARTICLE_COMMAND_MS = 'ARTICLE_COMMAND';

export const API_USER_QUERY_MS = 'USER_QUERY';
export const API_USER_COMMAND_MS = 'USER_COMMAND';

export const API_TODO_QUERY_MS = 'TODO_QUERY';
export const API_TODO_COMMAND_MS = 'TODO_COMMAND';
