export const API_ARTICLE_QUERY_MS = 'ARTICLE_QUERY';
export const API_ARTICLE_COMMAND_MS = 'ARTICLE_COMMAND';

export const API_USER_QUERY_MS = 'USER_QUERY';
export const API_USER_COMMAND_MS = 'USER_COMMAND';

export const API_TODO_QUERY_MS = 'TODO_QUERY';
export const API_TODO_COMMAND_MS = 'TODO_COMMAND';

export const API_MEMBERSHIP_QUERY_MS = 'MEMBERSHIP_QUERY';
export const API_MEMBERSHIP_COMMAND_MS = 'MEMBERSHIP_COMMAND';

export const API_ORGANIZATION_QUERY_MS = 'ORGANIZATION_QUERY';
export const API_ORGANIZATION_COMMAND_MS = 'ORGANIZATION_COMMAND';
