export const API_ARTICLE_QUERY_MS = 'ARTICLE_QUERY';
export const API_ARTICLE_COMMAND_MS = 'ARTICLE_COMMAND';

export const API_TODO_QUERY_MS = 'TODO_QUERY';
export const API_TODO_COMMAND_MS = 'TODO_COMMAND';

export const API_MEMBERSHIP_QUERY_MS = 'MEMBERSHIP_QUERY';
export const API_MEMBERSHIP_COMMAND_MS = 'MEMBERSHIP_COMMAND';
