#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BASE=$(git merge-base main HEAD) 
FILES=$(git diff --name-only $BASE HEAD | xargs)

if [ -z "$FILES" ]
then
    pnpm format
    pnpm lint --filter=\!blog
else
    pnpm format -- $FILES
    pnpm lint --filter=\!blog -- $FILES
fi
